"""add farm flock sensor_reading tables

Revision ID: 76def4169d56
Revises: be00a17305e1
Create Date: 2026-08-08 21:50:30.771154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76def4169d56'
down_revision: Union[str, Sequence[str], None] = 'be00a17305e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SAFE', 'WARNING', 'CRITICAL', name='farmstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_owner_id'), 'farms', ['owner_id'], unique=False)
    op.create_table('flocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('bird_type', sa.Enum('BROILER', 'LAYER', name='birdtype'), nullable=False),
    sa.Column('bird_count', sa.Integer(), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=False),
    sa.Column('placement_date', sa.Date(), nullable=True),
    sa.Column('vaccination_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flocks_farm_id'), 'flocks', ['farm_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('ammonia', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_farm_id'), 'sensor_readings', ['farm_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_farm_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_flocks_farm_id'), table_name='flocks')
    op.drop_table('flocks')
    op.drop_index(op.f('ix_farms_owner_id'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
