"""add medication guidance table

Revision ID: 0997654b8c89
Revises: 29e565e1b255
Create Date: 2026-09-26 13:52:15.890333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0997654b8c89'
down_revision: Union[str, Sequence[str], None] = '29e565e1b255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_guidance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('disease', sa.Enum('HEALTHY', 'COCCIDIOSIS', 'NEWCASTLE', 'SALMONELLOSIS', name='disease_type'), nullable=False),
    sa.Column('medication_name', sa.String(length=150), nullable=False),
    sa.Column('active_ingredient', sa.String(length=150), nullable=True),
    sa.Column('indication', sa.Text(), nullable=False),
    sa.Column('dosage_value', sa.Float(), nullable=True),
    sa.Column('dosage_unit', sa.String(length=100), nullable=True),
    sa.Column('administration_method', sa.String(length=150), nullable=True),
    sa.Column('treatment_duration_days', sa.Integer(), nullable=True),
    sa.Column('withdrawal_period_days', sa.Integer(), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.Column('veterinarian_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_guidance_disease'), 'medication_guidance', ['disease'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_guidance_disease'), table_name='medication_guidance')
    op.drop_table('medication_guidance')
    # ### end Alembic commands ###
