"""add average weight to flocks

Revision ID: 29e565e1b255
Revises: 4f2074154c47
Create Date: 2026-09-26 13:44:22.742616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e565e1b255'
down_revision: Union[str, Sequence[str], None] = '4f2074154c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flocks', sa.Column('average_weight_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flocks', 'average_weight_kg')
    # ### end Alembic commands ###
