"""add medication source fields

Revision ID: e4efd5a426fd
Revises: 0997654b8c89
Create Date: 2026-09-30 09:45:10.280997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4efd5a426fd'
down_revision: Union[str, Sequence[str], None] = '0997654b8c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_guidance', sa.Column('source_name', sa.String(length=200), nullable=True))
    op.add_column('medication_guidance', sa.Column('source_reference', sa.Text(), nullable=True))
    op.add_column('medication_guidance', sa.Column('product_formulation', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_guidance', 'product_formulation')
    op.drop_column('medication_guidance', 'source_reference')
    op.drop_column('medication_guidance', 'source_name')
    # ### end Alembic commands ###
