// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5GXks3hE0_u664NXSS6GYYnhZUMWPABc',
    appId: '1:413965063456:web:1064c5123aba0d26e9f345',
    messagingSenderId: '413965063456',
    projectId: 'poultyguard',
    authDomain: 'poultyguard.firebaseapp.com',
    storageBucket: 'poultyguard.firebasestorage.app',
    measurementId: 'G-HSSYD48Z63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLswAMDMex7Lt9Jmtf0iCh1MD9xKGH3z0',
    appId: '1:413965063456:android:c075261735ec66f9e9f345',
    messagingSenderId: '413965063456',
    projectId: 'poultyguard',
    storageBucket: 'poultyguard.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmYg0Ojupha0MugvNXJdW6aW5moDmJjPU',
    appId: '1:413965063456:ios:17343c8403ff8e88e9f345',
    messagingSenderId: '413965063456',
    projectId: 'poultyguard',
    storageBucket: 'poultyguard.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmYg0Ojupha0MugvNXJdW6aW5moDmJjPU',
    appId: '1:413965063456:ios:17343c8403ff8e88e9f345',
    messagingSenderId: '413965063456',
    projectId: 'poultyguard',
    storageBucket: 'poultyguard.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5GXks3hE0_u664NXSS6GYYnhZUMWPABc',
    appId: '1:413965063456:web:d4e6e3c18d4db30fe9f345',
    messagingSenderId: '413965063456',
    projectId: 'poultyguard',
    authDomain: 'poultyguard.firebaseapp.com',
    storageBucket: 'poultyguard.firebasestorage.app',
    measurementId: 'G-FCP77YRT3Y',
  );
}
